# Generated by Django 4.1.5 on 2023-01-30 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_2', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_2.employee'),
        ),
    ]
