# Generated by Django 4.1.5 on 2023-01-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_2', '0003_alter_employee_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='course_set', to='app_2.course'),
        ),
    ]
