# Generated by Django 4.1.5 on 2023-01-28 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('code', models.AutoField(db_column='Code', primary_key=True, serialize=False)),
                ('libelle', models.TextField(db_column='Libelle', unique=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
            ],
            options={
                'db_table': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('code', models.CharField(db_column='Code', max_length=255, primary_key=True, serialize=False)),
                ('societe', models.TextField(db_column='Societe', unique=True)),
                ('contact', models.TextField(blank=True, db_column='Contact', null=True)),
                ('fonction', models.TextField(blank=True, db_column='Fonction', null=True)),
                ('adresse', models.TextField(blank=True, db_column='Adresse', null=True)),
                ('ville', models.TextField(blank=True, db_column='Ville', null=True)),
                ('region', models.TextField(blank=True, db_column='Region', null=True)),
                ('code_postal', models.CharField(blank=True, db_column='Code_postal', max_length=255, null=True)),
                ('pays', models.TextField(blank=True, db_column='Pays', null=True)),
                ('telephone', models.TextField(blank=True, db_column='Telephone', null=True)),
                ('fax', models.TextField(blank=True, db_column='Fax', null=True)),
            ],
            options={
                'db_table': 'Client',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('numero', models.AutoField(db_column='Numero', primary_key=True, serialize=False)),
                ('saisiele', models.DateField(db_column='SaisieLe')),
                ('envoyeele', models.DateField(blank=True, db_column='EnvoyeeLe', null=True)),
                ('port', models.DecimalField(blank=True, db_column='Port', decimal_places=5, max_digits=10, null=True)),
                ('destinataire', models.TextField(blank=True, db_column='Destinataire', null=True)),
                ('adresse_livraison', models.TextField(blank=True, db_column='Adresse_livraison', null=True)),
                ('ville_livraison', models.TextField(blank=True, db_column='Ville_livraison', null=True)),
                ('region_livraison', models.TextField(blank=True, db_column='Region_livraison', null=True)),
                ('code_postal_livraison', models.TextField(blank=True, db_column='Code_Postal_livraison', null=True)),
                ('pays_livraison', models.TextField(blank=True, db_column='Pays_Livraison', null=True)),
                ('remise', models.DecimalField(db_column='Remise', decimal_places=5, max_digits=10)),
                ('client', models.ForeignKey(db_column='Client', on_delete=django.db.models.deletion.DO_NOTHING, related_name='commandes', related_query_name='commande', to='comptoirs_app.client')),
            ],
            options={
                'db_table': 'Commande',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('reference', models.AutoField(db_column='Reference', primary_key=True, serialize=False)),
                ('nom', models.TextField(db_column='Nom', unique=True)),
                ('fournisseur', models.IntegerField(db_column='Fournisseur')),
                ('quantite_par_unite', models.TextField(blank=True, db_column='Quantite_par_unite', null=True)),
                ('prix_unitaire', models.DecimalField(db_column='Prix_unitaire', decimal_places=5, max_digits=10)),
                ('unites_en_stock', models.SmallIntegerField(db_column='Unites_en_stock')),
                ('unites_commandees', models.SmallIntegerField(db_column='Unites_commandees')),
                ('niveau_de_reappro', models.SmallIntegerField(db_column='Niveau_de_reappro')),
                ('indisponible', models.SmallIntegerField(db_column='Indisponible')),
                ('categorie', models.ForeignKey(db_column='Categorie', on_delete=django.db.models.deletion.DO_NOTHING, related_name='categories', related_query_name='categorie', to='comptoirs_app.categorie')),
            ],
            options={
                'db_table': 'Produit',
            },
        ),
        migrations.CreateModel(
            name='Ligne',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('quantite', models.SmallIntegerField(db_column='Quantite')),
                ('commande', models.ForeignKey(db_column='Commande', on_delete=django.db.models.deletion.DO_NOTHING, related_name='commande', related_query_name='commande', to='comptoirs_app.commande')),
                ('produit', models.ForeignKey(db_column='Produit', on_delete=django.db.models.deletion.DO_NOTHING, related_name='produit', related_query_name='produit', to='comptoirs_app.produit')),
            ],
            options={
                'db_table': 'Ligne',
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='produits',
            field=models.ManyToManyField(through='comptoirs_app.Ligne', to='comptoirs_app.produit'),
        ),
    ]
